
import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import {Theme, ThemePanel} from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import ThemeToggle from "@/components/thebase-ui/ThemeToggle"

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider attribute="class">
            <Theme accentColor="gray" grayColor="slate" radius="large" scaling="100%">
                {children}

                <ThemePanel/>

            </Theme>
        </ThemeProvider>
        </body>
        </html>
    );
}
